void _putchar(char c);
int _isupper();
int _isdigit();
void print_triangle();
int mul();
void print_numbers();
void print_most_numbers();
void more_numbers();
void print_line();
void print_diagonal();
void print_square(int size);
